CREATE DATABASE [ShahjTask]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShahjTask', FILENAME = N'/var/opt/mssql/data/ShahjTask.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShahjTask_log', FILENAME = N'/var/opt/mssql/data/ShahjTask_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ShahjTask] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [ShahjTask] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ShahjTask] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ShahjTask] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ShahjTask] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ShahjTask] SET ARITHABORT OFF 
GO
ALTER DATABASE [ShahjTask] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ShahjTask] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ShahjTask] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [ShahjTask] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ShahjTask] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ShahjTask] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ShahjTask] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ShahjTask] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ShahjTask] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ShahjTask] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ShahjTask] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ShahjTask] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ShahjTask] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ShahjTask] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ShahjTask] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ShahjTask] SET  READ_WRITE 
GO
ALTER DATABASE [ShahjTask] SET RECOVERY FULL 
GO
ALTER DATABASE [ShahjTask] SET  MULTI_USER 
GO
ALTER DATABASE [ShahjTask] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ShahjTask] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ShahjTask] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ShahjTask]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [ShahjTask]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ShahjTask] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
